# Generated by Django 5.1.1 on 2024-09-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
